# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
  - bao-test-ios-build
  
pool:
  vmImage: 'macos-10.14'
  
# variables:
#   configuration: Debug
#   sdk: iphoneos
  
steps:
# - task: InstallAppleCertificate@2
#   inputs:
#     certSecureFile: '$(p12FileName)'
#     certPwd: '$(p12Password)'
#     keychain: 'temp'
#     deleteCert: true  

# - task: InstallAppleProvisioningProfile@1
#   inputs:
#     provisioningProfileLocation: 'secureFiles'
#     provProfileSecureFile: '$(provisioningProfile)'
#     removeProfile: true

# skip this step because there is no Pods in project.
#- task: CocoaPods@0
#  inputs:
#    forceRepoUpdate: false

# - task: Xcode@5
#   inputs:
#     actions: 'build'
#     scheme: 'FarmerRecruitmentApp'
#     sdk: '$(sdk)'
#     configuration: '$(configuration)'
#     xcWorkspacePath: 'ios/FarmerRecruitmentApp.xcworkspace'
#     xcodeVersion: 'default'
#     packageApp: true
#     signingOption: 'manual' # Optional. Options: nosign, default, manual, auto
#     signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
#     provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'

# - task: CopyFiles@2
#   inputs:
#     contents: '**/*.ipa'
#     targetFolder: '$(build.artifactStagingDirectory)'
#     overWrite: true

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathtoPublish: '$(build.artifactStagingDirectory)/output/$(sdk)/$(configuration)' 
#     artifactName: 'ipas' 
#     publishLocation: 'Container'


- task: Xcode@5
  displayName: 'Build the app using Xcode'
  inputs:
    actions: 'clean build analyze archive'
    sdk: 'iphoneos'
    scheme: 'FarmerRecruitmentApp'
    configuration: 'Debug'
    xcWorkspacePath: 'ios/FarmerRecruitmentApp.xcworkspace'
    xcodeVersion: 'default'
    useXcpretty: false
    args: '-archivePath $(build.artifactStagingDirectory)/FarmerRecruitmentApp'